analyzer:
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints

include: package:pedantic/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: false
